Repository schubergphilis/terraform-azure-mcaf-storage-account, pull requests merged in 2025-02, with the labels that each got.

#9 bug: typo in PrivateLink
  README.md
  variables.tf
Labels: bug

#10 enhancement: adding file share creation
  README.md
  main.tf
  variables.tf
Labels: feature

#11 feat: change types from list to set
  README.md
  variables.tf
Labels: feature

#12 enhancement: Share security options
  README.md
  examples/basic/main.tf
  main.tf
  variables.share.tf
  variables.tf
Labels: enhancement, feature

#13 enhancement: retention policy shares
  README.md
  examples/basic/main.tf
  main.tf
  variables.share.tf
Labels: feature

#16 feature: Add option to backup blob storage
  README.md
  main.tf
  outputs.tf
  variables.tf
Labels: feature

#17 feat: Enabling Local user creation (SFTP Enabled : true)
  README.md
  main.tf
  variables.tf
Labels: feature

#21 fix: Storagebackup
  README.md
  main.tf
  variables.tf
Labels: bug, fix
